force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Invoice__c/Book_Invoice__c.object-meta.xml
<CustomObject>
    <label>Book Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Invoice__c/fields/Book_detail__c.field-meta.xml
<CustomField>
    <fullName>Book_detail__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Book Detail</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Book Invoices</relationshipLabel>
    <relationshipName>Book_Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book_Invoice__c/fields/Quatity__c.field-meta.xml
<CustomField>
    <fullName>Quatity__c</fullName>
    <label>Quatity</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CreateTaskForBookSell.cls
public class CreateTaskForBookSell {
    @InvocableMethod
    public static void createTask(List<Id> invoiceIds) {
        String sub ;
        Id bookId; 
        String bookName;

        for (Id invoiceId : invoiceIds ) {
            //Get Book details from Invoice 
            Book_Invoice__c  bookInv = [SELECT Book_detail__c, Quatity__c FROM Book_Invoice__c WHERE Id=:invoiceId];
            bookId = bookInv.Book_detail__c;
            //Get Book name from Book sObject
            Book__c book = [SELECT Name FROM Book__c where Id=:bookId];
            bookName = book.Name;

            //Create subject string for the Task which will be created once the book is sold
            sub = 'Sold book '+bookName+' of Quantity '+bookInv.Quatity__c;
            Task task = new Task(WhatId=invoiceId, Status='Completed',Subject=sub);
        	insert task;

            //freeing up space 
            bookInv = null;
            book = null;
        }
    }
}