force-app/main/default/objects/Merchandise__c/Merchandise__c.object-meta.xml
<CustomObject>
    <description>Merchandise</description>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sale_Item__c/Sale_Item__c.object-meta.xml
<CustomObject>
    <label>Sale Item</label>
    <nameField>
        <label>Sale Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sale Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sale_Item__c/fields/Merchandise__c.field-meta.xml
<CustomField>
    <fullName>Merchandise__c</fullName>
    <description>Merchandise Name</description>
    <label>Merchandise</label>
    <referenceTo>Merchandise__c</referenceTo>
    <relationshipLabel>Sale Items</relationshipLabel>
    <relationshipName>Sale_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sale_Item__c/fields/SellItem_Desc__c.field-meta.xml
<CustomField>
    <fullName>SellItem_Desc__c</fullName>
    <description>SellItem Desc</description>
    <inlineHelpText>SellItem Desc</inlineHelpText>
    <label>SellItem Desc</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sale_Item__c/fields/SellItem_Stock__c.field-meta.xml
<CustomField>
    <fullName>SellItem_Stock__c</fullName>
    <description>SellItem Stock</description>
    <inlineHelpText>SellItem Stock</inlineHelpText>
    <label>SellItem Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sale_Item__c/fields/SelttItem_Price__c.field-meta.xml
<CustomField>
    <fullName>SelttItem_Price__c</fullName>
    <description>SelttItem Price</description>
    <inlineHelpText>SelttItem Price</inlineHelpText>
    <label>SelttItem Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ListOfSales.cls
public class ListOfSales {
    
    List <Sale_Item__c> ls;
    Map <Integer, List<Sale_Item__c>> mp;
    public static integer cnt;
    
    public ListOfSales() {
        mp = new Map <Integer, List<Sale_Item__c>> ();
        cnt = 0;
    }
    public void setSalesItems() {
        
        list <Merchandise__c> ml = [SELECT Id FROM Merchandise__c]; 
        //system.debug(ml);
        for (Merchandise__c m: ml) {
           ls = [SELECT Name, SellItem_Desc__c,SellItem_Stock__c,SelttItem_Price__c FROM Sale_Item__c WHERE Merchandise__c =:+m.Id];
           cnt = cnt +1 ;
           mp.put(cnt, ls);
           //system.debug(ls);
        }
        
    }
    public void print() {
        Set <Integer> s = mp.keySet();
        system.debug(mp);
        for (Integer a: s) {
            //system.debug(mp.get(a));
            
            for (Sale_Item__c sis: mp.get(a)) {
                
                system.debug(sis.Name);
            }
        }
    }    
}